name: build-and-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Yandex Object Storage
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --no-progress --acl public-read --endpoint-url ${{ vars.ENDPOINT_URL || 'https://storage.yandexcloud.net' }}
        env:
          # Sanitize long dashes to ASCII hyphen-minus just in case
          AWS_S3_BUCKET: ${{ replace(replace(secrets.S3_BUCKET || vars.BUCKET_NAME, '–', '-'), '—', '-') }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || vars.AWS_REGION }}
          SOURCE_DIR: 'dist'

      - name: Verify uploaded files
        env:
          BUCKET: ${{ replace(replace(secrets.S3_BUCKET || vars.BUCKET_NAME, '–', '-'), '—', '-') }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || vars.AWS_REGION }}
          ENDPOINT: ${{ vars.ENDPOINT_URL || 'https://storage.yandexcloud.net' }}
        run: |
          sudo apt-get update && sudo apt-get install -y awscli >/dev/null
          echo "Listing bucket root:" && aws s3 ls s3://$BUCKET/ --endpoint-url $ENDPOINT || true
          echo "Check index.html:" && aws s3 ls s3://$BUCKET/index.html --endpoint-url $ENDPOINT || true
