name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Validate secrets
        run: |
          test -n "$S3_BUCKET" || (echo "Missing secret: S3_BUCKET" && exit 1)
          test -n "$AWS_ACCESS_KEY_ID" || (echo "Missing secret: AWS_ACCESS_KEY_ID" && exit 1)
          test -n "$AWS_SECRET_ACCESS_KEY" || (echo "Missing secret: AWS_SECRET_ACCESS_KEY" && exit 1)
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Yandex Object Storage
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --no-progress --acl public-read --endpoint-url https://storage.yandexcloud.net
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'ru-central1' }}
          SOURCE_DIR: 'dist'
