name: Deploy to Yandex Object Storage (logo)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_LOGO }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_LOGO }}
      AWS_REGION: ru-central1
      AWS_DEFAULT_REGION: ru-central1
      AWS_EC2_METADATA_DISABLED: true
      AWS_S3_FORCE_PATH_STYLE: true
      S3_ENDPOINT: https://storage.yandexcloud.net
      S3_BUCKET: xn--80aabn.xn--80avakjqg.xn--p1ai   # лого.роллаут.рф

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Debug AWS CLI and connectivity
        run: |
          aws --version
          echo "AccessKeyId length: ${#AWS_ACCESS_KEY_ID}"
          echo "Secret length: ${#AWS_SECRET_ACCESS_KEY}"
          echo "Bucket: $S3_BUCKET"
          echo "Listing bucket root (may fail if creds invalid):"
          aws s3 ls "s3://$S3_BUCKET/" --endpoint-url "$S3_ENDPOINT" || true

      - name: Upload static assets (immutable)
        run: |
          aws s3 sync ./dist "s3://$S3_BUCKET/" \
            --endpoint-url "$S3_ENDPOINT" \
            --exclude "*.html" \
            --cache-control "public, max-age=31536000, immutable" \
            --acl public-read \
            --delete

      - name: Upload HTML (no-cache)
        run: |
          aws s3 sync ./dist "s3://$S3_BUCKET/" \
            --endpoint-url "$S3_ENDPOINT" \
            --exclude "*" --include "*.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --acl public-read
